#ifndef RTW_HEADER_Approx_Multiplier_M2_AMA2_NAB12_capi_h
#define RTW_HEADER_Approx_Multiplier_M2_AMA2_NAB12_capi_h
#include "Approx_Multiplier_M2_AMA2_NAB12.h"
extern void Approx_Multiplier_M2_AMA2_NAB12_InitializeDataMapInfo ( void ) ;
#endif
